### PR TITLE
Add additional graylog checks/metrics

### PR DESCRIPTION
**Pull request by esell**
This PR adds a new check for the internal graylog "processing" buffers as well as some metrics for the internal kafka disk journal. 
We are not a ruby shop so everything was done in python :(

### CODE REVIEW

**Comment by mattyjones** [comment]
Can you please update the CHANGELOG. Thanks! @esell

**Comment by esell** [comment]
No problem, would you like me to update the version to `0.1.0` as well since this will [add functionality in a backwards-compatible manner](http://semver.org/)

**Comment by eheydrick** [comment]
@esell put the changelog entries under the unreleased section and we'll bump the version at next release time.

**Comment by layered-esell** [comment]
This totally fell off my radar, apologies. The changelog has been updated...

**Pull request merged**
